"""This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://mtg.wiki
  name = mtg

Please do not commit this to the Git repository!
"""

from pywikibot import family


class Family(family.Family):  # noqa: D101
    name = "mtg"
    langs = {
        "en": "mtg.wiki",
    }

    def scriptpath(self, code):
        return {
            "en": "",
        }[code]

    def protocol(self, code):
        return {
            "en": "https",
        }[code]
